require: rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - "node_modules/**/*"
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - "log/**/*"
    - 'vendor/**/*'
    - 'tmp/**/*'

Documentation:
  Enabled: false
